window:
  dimensions:
    columns: 80
    lines: 24
  dynamic_title: true
  dynamic_padding: true

scrolling:
  history: 0

font:
  normal:
    family: JetBrainsMono Nerd Font
  size: 14

mouse:
  hide_when_typing: true

key_bindings:
  # alacritty/alacritty#1073
  - { key: Key3, mods: Alt, chars: "\x23" }

# Colors (Wombat)
colors:
  # Default colors
  primary:
    background: '0x1f1f1f'
    foreground: '0xe5e1d8'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xf7786d'
    green:   '0xbde97c'
    yellow:  '0xefdfac'
    blue:    '0x6ebaf8'
    magenta: '0xef88ff'
    cyan:    '0x90fdf8'
    white:   '0xe5e1d8'

  # Bright colors
  bright:
    black:   '0xb4b4b4'
    red:     '0xf99f92'
    green:   '0xe3f7a1'
    yellow:  '0xf2e9bf'
    blue:    '0xb3d2ff'
    magenta: '0xe5bdff'
    cyan:    '0xc2fefa'
    white:   '0xffffff'
