keys:
  - &personal age19ndv83pvgryxmk2ndd3fy49jpx4hra5au3zu0vhw0f24splxnu7sq8mtz6
  - &employer_emed age14ddy9t7d0dnlmrumefw45ft9jqvzwz6l9d2th8hfd738xhjluckskuhe7p
creation_rules:
  - path_regex: ^secrets/employer-emed\.yaml$
    age: *employer_emed
  - path_regex: ^secrets/personal\.yaml$
    age: *personal
