keys:
  - &me age19ndv83pvgryxmk2ndd3fy49jpx4hra5au3zu0vhw0f24splxnu7sq8mtz6
  - &f1xable age1u82l2vw5s9upca8l9wukq2r4w2hj6yce8wcm4z5jw9ujccen5cas7svwkx
  - &fatman age1tsypj2vpuy6dnlx3le2225l39knhm43xzsxqm57wdwh29t5vj3vq70h0c7
  - &employer_emed age14ddy9t7d0dnlmrumefw45ft9jqvzwz6l9d2th8hfd738xhjluckskuhe7p
  - &employer_emed_b-4653 age1jklllmcjlj8ln8jfrdmp2scg2q93tkk3msnsc5jxcjsamwp5vdgshwr7my
recipients:
  - &emed >-
    age14ddy9t7d0dnlmrumefw45ft9jqvzwz6l9d2th8hfd738xhjluckskuhe7p,
    age1jklllmcjlj8ln8jfrdmp2scg2q93tkk3msnsc5jxcjsamwp5vdgshwr7my
  - &personal >-
    age19ndv83pvgryxmk2ndd3fy49jpx4hra5au3zu0vhw0f24splxnu7sq8mtz6,
    age1u82l2vw5s9upca8l9wukq2r4w2hj6yce8wcm4z5jw9ujccen5cas7svwkx,
    age1tsypj2vpuy6dnlx3le2225l39knhm43xzsxqm57wdwh29t5vj3vq70h0c7
creation_rules:
  - path_regex: ^secrets/employer-emed\.yaml$
    age: *emed
  - path_regex: ^secrets/personal\.yaml$
    age: *personal
