import = [
  "~/.config/alacritty/themes/themes/tokyo-night-storm.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[mouse]
hide_when_typing = true

[scrolling]
history = 0

[window]
dynamic_padding = true
dynamic_title = true
option_as_alt = "both"

[window.dimensions]
columns = 80
lines = 24
